name: save_image_to_album
description: Sample App for Save image to Album.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  wechat_assets_picker:
  path_provider:
  external_path:
  collection:
  http:
  intl:
  fluttertoast:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
